import { When, And, Then } from 'cypress-cucumber-preprocessor/steps';
import ManageStudiesPage from '../../../pageobjects/studies/manage-studies-page'
import CreateStudyPage from '../../../pageobjects/studies/create-study-page';
import { randomString } from '../../../../support/commands';
import PlotVisualizationPage from '../../../pageobjects/studies/plot-visualization-page';

const manageStudiesPage = new ManageStudiesPage()
const createStudyPage = new CreateStudyPage()
const plotVisualizationPage = new PlotVisualizationPage()

const studyName = 'Study-' + randomString();

const generateRCBDesign = () => {
    createStudyPage.goToExperimentalDesign(false);
    createStudyPage.generateRCBDesign();
}

And('I create a trial using randomized complete block design with treatment factors',  () => {
    manageStudiesPage.startNewStudy();
    createStudyPage.startNewStudyWithObservations(studyName,
        'Study with Randomized Complete Block Design',
        'Trial', 'This is an autogenerated study from Cypress e2e testing for graphical query.',
        'Aflatox_M_ppb');
    createStudyPage.addObservations('ASI_Cmp_day'); // additional numeric observation
});

When('I navigate to plot visualization screen',  () => {
    plotVisualizationPage.openPlotVisualizationModal();
});

And('I select Scatterplot as plot type',  () => {
    plotVisualizationPage.selectPlotType();
});

And('I select Auto as regression method',  () => {
    plotVisualizationPage.selectRegressionMethod();
});

And('I select variable on X and Y',  () => {
    plotVisualizationPage.selectXYVariable();
});

And('I generate plot visualization',  () => {
    plotVisualizationPage.generatePlotVisualization();
});

Then('a plot visualization graph should display',  () => {
    plotVisualizationPage.verifyGenerateSuccess();
});
