import { When,And,Then } from "cypress-cucumber-preprocessor/steps";
import ManageStudiesPage from '../../../pageobjects/studies/manage-studies-page'
import CreateStudyPage from '../../../pageobjects/studies/create-study-page';

const manageStudiesPage = new ManageStudiesPage()
const createStudyPage = new CreateStudyPage()

const studyName = Cypress.env('existingStudyName');

const randStudyName = 'Study-' + Math.random().toString(20).replace(/[^a-z]+/g, '');

const generateRCBDesign = () => {
    createStudyPage.goToExperimentalDesign(false);
    createStudyPage.generateRCBDesign();
}

const startNewStudy = () => {
    manageStudiesPage.startNewStudy();
    createStudyPage.saveStudyWithBasicDetails(randStudyName, 'Study with Randomized Complete Block Design',
        'Trial', 'This is an autogenerated study from Cypress e2e testing.');
}

And('I opened an existing study with germplasm list but with no existing design yet',()=>{
    manageStudiesPage.browseExistingStudies();
    manageStudiesPage.selectExistingStudy(studyName);
})

And('I generated experimental design using Randomized Complete Block design',() => {
    createStudyPage.goToExperimentalDesign(false);
    createStudyPage.generateRCBDesign();
    createStudyPage.confirmGenerateModal();
})

When('I try to generate experimental design using Randomized Complete Block design',() => {
    createStudyPage.goToExperimentalDesign(false);
    createStudyPage.generateRCBDesign();
})

When('I go to experimental design and generated using Randomized Complete Block design',()=>{
    createStudyPage.goToExperimentalDesign(true);
    createStudyPage.generateRCBDesign();
    createStudyPage.confirmGenerateModal();
})

Then('Design generation should be successful',()=>{
    createStudyPage.checkGenerateDesignSuccess();
})

And('Delete the generated design',()=>{
    createStudyPage.deleteGeneratedDesign();
})

When('I created a new study with basic details',startNewStudy)

And('I added study settings',()=>{
    createStudyPage.addStudySettings();
})

And('I browsed germplasm list',()=>{
    createStudyPage.addGermplasms();
})

And('I added treatment factors',()=>{
    createStudyPage.addTreatmentFactors();
})

And('I added environment variables',()=>{
    createStudyPage.addEnvironmentVariables();
})

Then('Design generation should not be successful',()=>{
    createStudyPage.checkGenerateDesignFailure();
})
