import { When, And, Then } from 'cypress-cucumber-preprocessor/steps';
import ManageStudiesPage from '../../../pageobjects/studies/manage-studies-page'
import CreateStudyPage from '../../../pageobjects/studies/create-study-page';
import { randomString } from '../../../../support/commands';
import GraphicalQueryPage from '../../../pageobjects/graphical-query/graphical-query-page';

const manageStudiesPage = new ManageStudiesPage()
const createStudyPage = new CreateStudyPage()
const graphicalQueryPage = new GraphicalQueryPage()

const studyName = 'Study-' + randomString();

And('I create a trial using randomized complete block design with treatment factors',  () => {
    manageStudiesPage.startNewStudy();
    createStudyPage.startNewStudyWithObservations(studyName,
        'Study with Randomized Complete Block Design',
        'Trial', 'This is an autogenerated study from Cypress e2e testing for graphical query.',
        'Aflatox_M_ppb');
});

When('I selected a study name with existing observation',  () => {
    graphicalQueryPage.selectStudyName(studyName);
});

And('I selected PLOT as observation level',  () => {
    graphicalQueryPage.selectObservationLevel();
});

And('I loaded the query by graphical filtering',  () => {
    graphicalQueryPage.clickLoadQuery();
});

And('I selected a range of values for trait in the Where section',  () => {
    graphicalQueryPage.addRangeOfValues('Aflatox_M_ppb');
});

And('I exported the data by overall average',  () => {
    graphicalQueryPage.exportByOverallAverage();
});

Then('The export file should be downloaded',  () => {
    graphicalQueryPage.verifyExportSuccess();
});
