import { When, And, Then } from 'cypress-cucumber-preprocessor/steps';
import ManageStudiesPage from '../../../pageobjects/studies/manage-studies-page'
import CreateStudyPage from '../../../pageobjects/studies/create-study-page';
import CreateFieldmapPage from '../../../pageobjects/studies/create-fieldmap-page';
import CreateGeoreferencePage from '../../../pageobjects/studies/create-georeference-page';

const manageStudiesPage = new ManageStudiesPage();
const createStudyPage = new CreateStudyPage();
const createFieldmapPage = new CreateFieldmapPage();
const createGeoreferencePage = new CreateGeoreferencePage();

When('I make a study with fieldmap', () => {
    manageStudiesPage.startNewStudy();
    createStudyPage.createStudy('Study-' + Math.random().toString(20).replace(/[^a-z]+/g, ''),
        'Study with Randomized Complete Block Design',
        'Trial', 'This is an autogenerated study from Cypress e2e testing for georeference creation.');
    createStudyPage.waitForStudyToLoad();
    createStudyPage.clickStudyAction('Make field map', 'Field map options');
    createStudyPage.selectFielmapLocations();
    createFieldmapPage.createFieldmap();
    //comment out for testing without creating a new study
    //manageStudiesPage.browseExistingStudies();
    //manageStudiesPage.selectExistingStudy('Study-jaacjje');
})

And('I navigate to create reference screen', () => {
    createStudyPage.waitForStudyToLoad();
    createStudyPage.clickStudyAction('Create georeference', 'Field map options');
})

And('I select an environment', () => {
    createGeoreferencePage.selectEnvironment();
})

And('I draw a rectangle', () => {
    createGeoreferencePage.drawRectangle();
})

And('I load the details', () => {
    createGeoreferencePage.loadDetails();
})

And('I save the details', () => {
    createGeoreferencePage.saveDetails();
})

Then('A success that says plots are updated should display', () => {
    createGeoreferencePage.plotsUpdatedSuccess();
})
