import { When, And, Then } from 'cypress-cucumber-preprocessor/steps';
import { randomString } from '../../../../support/commands';
import CreateFieldmapPage from '../../../pageobjects/studies/create-fieldmap-page';
import CreateStudyPage from '../../../pageobjects/studies/create-study-page';
import ManageStudiesPage from '../../../pageobjects/studies/manage-studies-page'

const manageStudiesPage = new ManageStudiesPage();
const createStudyPage = new CreateStudyPage();
const createFieldmapPage = new CreateFieldmapPage();

When('I created a new study with basic details',  () => {
    manageStudiesPage.startNewStudy();
    createStudyPage.saveStudyWithBasicDetails('Study-' + Math.random().toString(20).replace(/[^a-z]+/g, ''),
        'Study with Randomized Complete Block Design',
        'Trial', 'This is an autogenerated study from Cypress e2e testing.');
});

And('I browsed germplasm list', () => {
    createStudyPage.addGermplasms();
});

And('I generated experimental design using Randomized Complete Block design', () => {
    createStudyPage.goToExperimentalDesign(false);
    createStudyPage.generateRCBDesign();
    createStudyPage.confirmGenerateModal();
});

And('Design generation is successful', () => {
    createStudyPage.checkGenerateDesignSuccess();
});

Then('I should be directed back to the study', () => {
    createStudyPage.waitForStudyToLoad();
});

When('I click {} action from {}', (actionName, actionOptionsName) => {
    createStudyPage.clickStudyAction(actionName, actionOptionsName);
});

And('I click OK to navigate to fieldmap page', () => {
    createStudyPage.selectFielmapLocations();
    createFieldmapPage.waitForFieldmapPageToLoad();
});

And('I add field and block', () => {
    const fieldName = `Field-${randomString()}`;
    const blockName = `Block-${randomString()}`;
    createFieldmapPage.addFieldName(fieldName);
    createFieldmapPage.addBlockName(blockName);
});

And('I specify valid row, range and plot details', () => {
    createFieldmapPage.specifyNumberOfRowsAndRanges();
});

And('I navigate to planting details page', () => {
    createFieldmapPage.moveToPlantingDetailsPage();
    createFieldmapPage.waitForFieldmapPageToLoad();
});

And('I select row column layout order', () => {
    createFieldmapPage.specifyPlotLayoutOrder('1');
});

And('I navigate to generate fieldmap page', () => {
    createFieldmapPage.moveToGenerateFieldmapPage();
    createFieldmapPage.waitForFieldmapPageToLoad();
});

And('I click Finish', () => {
    createFieldmapPage.clickFinish();
});












